services:
  db:
    image: postgres:17-bookworm
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    container_name: db-postgres
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - '127.0.0.1:5432:5432'

volumes:
  db_data:
